const mongoose=require("mongoose")
const cartSchema=new mongoose.Schema({
    owner:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"userCollection"
    },
    items:[
        {
            product:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"productsCollection"
            },
            quantity:{
                type:Number,
                default:1
            },
            totalPrice:{
                type:Number,
                default:0
            },
            date:{
                type:Date,
                default:Date.now
            }
        }
    ],
    cartTotalPrice:{
        type:Number,
        default:0
    }
 })
 module.exports=mongoose.model("cartCollectiion",cartSchema)